version: '3'
services:
  client:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/noteme-client:latest
    environment:
      - REACT_APP_API_URL=http://${{ secrets.EC2_HOST }}:5000
    ports:
      - "3000:80"
    restart: always
  
  server:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/noteme-server:latest
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb+srv://himanshudhaka9166:I5eH1eqf4S9YFima@cluster1.ama8ond.mongodb.net
      - CORS_ORIGIN=http://${{ secrets.EC2_HOST }}:3000
      - JWT_SECRET=asdfadf22k23h4kj2h4kh223
      - NODE_ENV=production
      - REACT_APP_API_URL=http://${{ secrets.EC2_HOST }}:5000
    ports:
      - "5000:5000"
    restart: always