version: '3'

services:
  client:
    image: ${DOCKERHUB_USERNAME}/noteme-client:latest
    ports:
      - "3000:80"
    restart: always

  server:
    image: ${DOCKERHUB_USERNAME}/noteme-server:latest
    ports:
      - "5000:5000"
    restart: always
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    restart: always

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    restart: always
    depends_on:
      - prometheus

volumes:
  mongo-data: