version: '3'

services:
  client:
    image: st3el/noteme-client:latest
    ports:
      - "3000:80"
    restart: always

  server:
    image: st3el/noteme-server:latest
    ports:
      - "5000:5000"
    restart: always
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://himanshudhaka9166:I5eH1eqf4S9YFima@cluster1.ama8ond.mongodb.net
      - CORS_ORIGIN=http://3.110.247.47:3000
      - NODE_ENV=production

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    restart: always
    depends_on:
      - prometheus